### ISSUE TITLE
Output Filename not overridable 

### ISSUE THREAD

**Issue by sklerotraficon** [MidEndProject/node-pdf2img#1]
As seen in the code, the output filename is hard-wired to "test_" (+pagenumber).

This is somewhat inconvenient and should be configurable in the output options.

This feature is listed in the Todo's

**Comment by fitraditya** [comment]
Ups, will fix it ASAP.

**Comment by sklerotraficon** [comment]
I could write that feature but running your test results in an "Error: File is not a PDF]":
npm test

> pdf2img@0.1.1 test /vagrant/node-pdf2img
> ./node_modules/.bin/mocha --reporter spec



  Split and covert pdf into images
/[MY_PATH]/node-pdf2img/test/test.pdf
[Error: File is not a PDF]

Could you please fix that ?
