### ISSUE TITLE
Conversion not working and failing tests

### ISSUE THREAD

**Issue by sklerotraficon** [MidEndProject/node-pdf2img#4]
Under NodeJs v0.10.36

1. Conversion does not work here, using the example code from the ReadMe. 

Error: [Error: File is not a PDF]

2. Running tests result in an "[Error: File is not a PDF]" on your enclosed test file: see below
npm test

pdf2img@0.1.1 test /[MY_PATH]/node-pdf2img
./node_modules/.bin/mocha --reporter spec
Split and covert pdf into images
/[MY_PATH]/node-pdf2img/test/test.pdf
[Error: File is not a PDF]
1) Create png files
/vagrant/node-pdf2img/test/test.pdf
[Error: File is not a PDF]
2) Create jpg files

0 passing (2m)
2 failing

1) Split and covert pdf into images Create png files:
Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test.

2) Split and covert pdf into images Create jpg files:
Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test.

npm ERR! weird error 2
npm ERR! not ok code 0

Could you please fix that ?

**Comment by fitraditya** [comment]
Try to increase timeout in test/index.js.
I can't reproduce this error using node 4.2.0.

**Comment by fitraditya** [comment]
Try to increase timeout in test/index.js.
I can't reproduce this error using node 4.2.0.

**Comment by sklerotraficon** [comment]
Timout is already at 60000ms ... so imho, that should not be the issue

**Comment by fitraditya** [comment]
I'll try to using node 0.10.36.

**Comment by fitraditya** [comment]
I still can't reproduce this issue.
![screenshot from 2016-01-29 14 15 27](https://cloud.githubusercontent.com/assets/5242430/12669408/e2a58f70-c692-11e5-8600-c5e7df9f6ce3.png)
