### ISSUE TITLE
Cannot set property 'page' of null

### ISSUE THREAD

**Issue by proreact-mj** [MidEndProject/node-pdf2img#6]
I have found a files that fails conversion

```
TypeError: Cannot set property 'page' of null
    at /[app_path]/node_modules/pdf2img/lib/pdf2img.js:66:23
```

If I echo out error right after convertPdf2Img has execute it show that the "datasize < 127" check fails, thus passing an error back, but the error is unhandled and crashes the server.

Need some kind of error handling wrapper around
```
          result.page = page; // <-- This fails as result is not set when an error occures in convertPdf2Img 
          callbackmap(null, result);
```

Problem example basic document converted from Word, attached
[1455011779_56191.pdf](https://github.com/MidEndProject/node-pdf2img/files/123052/1455011779_56191.pdf)
) 

**Every time an error is passed from convertPdf2Img it causes this unhandled exception to crash the server**

Pointers as to what is wrong with the file are also welcome :)

**Comment by proreact-mj** [comment]
If I just delete the datasize check it works. All pages are converted correctly, so something in the datasize check is not working as it should (3 resulting pages, all above 500kb).

this fixes this pdf, but the core issue is still that any error from convertPdf2Img causes an unhandled exception.

**Comment by fablife** [comment]
+1, We have a similar issue.

I wonder what the check 
```
107   result.on('end', function() {
108     if (datasize < 127) {
109       callback('[Error: Invalid data size]', null);
110     }
```
actually is for

**Comment by proreact-mj** [comment]
I'm moving towards another approach. Commanline comparison of GM (Graphics Magick) and GS (GhostScript) PDF to JPG conversion has show that GM imposes a massive overhead to (one test went from few secs on GS to over 30 secs in GM), and less error resilient in, the conversion process and in the end just delegates to GS anyway. So I'm cutting out the middleman :)

I would recommend looking into 3 aspects if this repo is to be maintained:
1. Validating the necessity of the datasize check
2. Make sure that errors from convertPdf2Img is handled
3. Consider using async.mapSeries instead og async.map, as a asynchronously converting a multipage document can drain server resources very fast. It is a very easy switch (just ad "Series" and everything still works) and while is does decrease conversion time by cirka 50%, it enables the sever to handle much larger files without problems.

**Comment by alexcroox** [comment]
I encountered this issue after installing from npm, however replacing with the master version in this repo fixed it. Are the fixes not published on npm yet? The change in master was from over 2 months ago

**Comment by fitraditya** [comment]
I removed `datasize` check. Hopefully it will fix this issue.
